### ISSUE TITLE
Update the repository name

### ISSUE THREAD

**Issue by programarivm** [chesslablab/engine#1]
The repository name should now be updated.

Happy coding and learning!

**Comment by programarivm** [comment]
Hey @EarlyEdition, thanks for your interest in creating a new project! Sorry that I couldn't figure out how to grant write permissions to a single user and ended up doing this. 

How would you want to rename this repo?

**Comment by EarlyEdition** [comment]
What is your suggestion for the best name about this repository?

**Comment by programarivm** [comment]
The repo has been renamed as engine for the time being.

**Comment by EarlyEdition** [comment]
Thank you, Jordi. I will soon start developing this repository.
